unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g status-position top
set -g status-interval 5
# Increase history limit, as we want an "almost" unlimited buffer.
# May be set to something even higher, like 250k
set -g history-limit 100000

set -g base-index 1 # start windows numbering at 1
set -g pane-base-index 1
set -g renumber-windows on

set -g set-titles on
set -g set-titles-string "#S:#W #{pane_current_command}"

set -g escape-time 0 

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugin/tmux-yank'

# vi mode
set-window-option -g mode-keys vi
# Selection key bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Tmuxifier
set -g @plugin 'jimeh/tmuxifier'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#{window_name} #{pane_current_command}"
set -g @catppuccin_window_current_text "#{window_name} #{pane_current_command}"

# Show the window list centered between the left and the right section
set-option -g status-justify absolute-centre

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_host}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
